import SwiftUI
import MapKit
import PhotosUI
import Charts

struct HomeView: View {
    @Environment(AppStore.self) private var store; @State private var showGuide = false
    private var todayCalories: Int { store.dashboard.nutritionLogs.reduce(0) { $0 + $1.calories } }
    var body: some View {
        ScrollView { VStack(spacing: 20) {
            HStack { VStack(alignment: .leading) { Text("Merhaba,").foregroundStyle(.secondary); Text(store.dashboard.profile.displayName).font(.largeTitle.bold()) }; Spacer(); NavigationLink { ProfileSettingsView() } label: { Image(systemName: "person.crop.circle.fill").font(.system(size: 42)).foregroundStyle(Color.hedefitGreen) } }
            HStack(spacing: 14) { ProgressRing(value: Double(store.dashboard.steps) / Double(store.settings.stepGoal), color: Color.hedefitGreen, title: "Adım", center: store.dashboard.steps.formatted()); ProgressRing(value: Double(store.dashboard.waterMl) / Double(store.settings.waterGoal), color: .blue, title: "Su", center: "\(store.dashboard.waterMl) ml"); ProgressRing(value: Double(todayCalories) / Double(store.dashboard.nutritionGoal.calories), color: Color.hedefitOrange, title: "Kalori", center: "\(todayCalories)") }.frame(maxWidth: .infinity).padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 22))
            LazyVGrid(columns: [.init(.flexible()), .init(.flexible())]) { MetricCard(title: "Seri", value: "\(store.dashboard.streakDays) gün", icon: "flame.fill", color: .orange); MetricCard(title: "Uyku", value: "\(store.dashboard.sleepMinutes / 60)s \(store.dashboard.sleepMinutes % 60)dk", icon: "moon.stars.fill", color: .purple); MetricCard(title: "Aktif enerji", value: "\(store.dashboard.activeCalories) kcal", icon: "bolt.heart.fill", color: .pink); MetricCard(title: "Haftalık XP", value: "\(store.dashboard.gamificationWeeklyXp ?? 0)", icon: "sparkles", color: .yellow) }
            VStack(spacing: 14) { SectionHeader(title: "Hızlı işlemler"); HStack { NavigationLink { RouteView() } label: { QuickAction(icon: "location.fill", title: "Rota") }; NavigationLink { ManualActivityView() } label: { QuickAction(icon: "plus.circle.fill", title: "Aktivite") }; NavigationLink { WorkoutCalendarView() } label: { QuickAction(icon: "calendar", title: "Takvim") }; NavigationLink { GameView() } label: { QuickAction(icon: "trophy.fill", title: "Oyun") } } }
            VStack(alignment: .leading, spacing: 12) { SectionHeader(title: "Bugünkü antrenman"); if store.dashboard.workouts.isEmpty { ContentUnavailableView("Programın hazır değil", systemImage: "dumbbell", description: Text("AI ile kişisel programını oluştur.")); Button("Program oluştur") { store.selectedTab = .workout }.buttonStyle(HedefitButtonStyle()) } else { ForEach(store.dashboard.workouts.prefix(4)) { ExerciseRow(exercise: $0) }; Button("Antrenmana git") { store.selectedTab = .workout }.buttonStyle(HedefitButtonStyle()) } }.padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 22))
            HStack { Button("Sağlık verilerini eşitle") { Task { await store.syncHealth() } }; Spacer(); Button("Yenile") { Task { await store.refresh() } } }.font(.subheadline)
        }.padding() }.navigationTitle("Hedefit").toolbar { ToolbarItem(placement: .topBarTrailing) { Button { showGuide = true } label: { Image(systemName: "questionmark.circle") } } }.sheet(isPresented: $showGuide) { UserGuideView() }.refreshable { await store.refresh() }
    }
}
struct QuickAction: View { let icon, title: String; var body: some View { VStack(spacing: 8) { Image(systemName: icon).font(.title2).foregroundStyle(Color.hedefitGreen); Text(title).font(.caption.bold()) }.frame(maxWidth: .infinity).padding(.vertical, 14).background(Color.panel, in: RoundedRectangle(cornerRadius: 16)) } }
struct ExerciseRow: View { let exercise: WorkoutExercise; var body: some View { HStack { Image(systemName: "dumbbell.fill").frame(width: 38, height: 38).background(Color.hedefitGreen.opacity(0.15), in: Circle()).foregroundStyle(Color.hedefitGreen); VStack(alignment: .leading) { Text(exercise.name).fontWeight(.semibold); Text("\(exercise.sets) set × \(exercise.reps) • \(exercise.area)").font(.caption).foregroundStyle(.secondary) }; Spacer(); Text("\(exercise.restSeconds) sn").font(.caption) } } }

struct WorkoutView: View {
    @Environment(AppStore.self) private var store; @State private var showActive = false; @State private var showLibrary = false; @State private var showManual = false
    var body: some View { ScrollView { VStack(spacing: 18) {
        if store.dashboard.workouts.isEmpty { ContentUnavailableView("Henüz program yok", systemImage: "figure.strengthtraining.traditional", description: Text("Profil değerlendirmene göre program oluşturabilir veya kütüphaneden hareket seçebilirsin.")); Button("AI programı oluştur") { store.message = "Program oluşturma isteği hazırlandı." }.buttonStyle(HedefitButtonStyle()) }
        else { HStack { VStack(alignment: .leading) { Text("Aktif program").font(.caption).foregroundStyle(.secondary); Text(store.dashboard.workoutPrograms.first(where: \.isActive)?.name ?? "Kişisel programım").font(.title2.bold()) }; Spacer(); Image(systemName: "figure.strengthtraining.traditional").font(.largeTitle).foregroundStyle(Color.hedefitGreen) }.padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 20)); ForEach(store.dashboard.workouts) { ExerciseRow(exercise: $0).padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 16)) }; Button("Antrenmanı başlat") { showActive = true }.buttonStyle(HedefitButtonStyle()).frame(maxWidth: .infinity) }
        HStack { Button { showLibrary = true } label: { Label("Egzersiz kütüphanesi", systemImage: "books.vertical.fill") }; Spacer(); Button { showManual = true } label: { Label("Aktivite ekle", systemImage: "plus.circle") } }.font(.subheadline).padding()
        if !store.dashboard.workoutPrograms.isEmpty { SectionHeader(title: "Programlarım"); ForEach(store.dashboard.workoutPrograms) { p in HStack { VStack(alignment: .leading) { Text(p.name).fontWeight(.semibold); Text("\(p.exercises.count) hareket • \(p.focusArea)").font(.caption).foregroundStyle(.secondary) }; Spacer(); if p.isActive { Image(systemName: "checkmark.circle.fill").foregroundStyle(Color.hedefitGreen) } }.padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 15)) } }
    }.padding() }.navigationTitle("Antrenman").fullScreenCover(isPresented: $showActive) { ActiveWorkoutView(exercises: store.dashboard.workouts) }.sheet(isPresented: $showLibrary) { NavigationStack { ExerciseLibraryView() } }.sheet(isPresented: $showManual) { NavigationStack { ManualActivityView() } } }
}

struct ActiveWorkoutView: View {
    @Environment(AppStore.self) private var store; @Environment(\.dismiss) private var dismiss; let exercises: [WorkoutExercise]
    @State private var index = 0; @State private var elapsed = 0; @State private var sets: [WorkoutSet] = []; @State private var feedback = WorkoutFeedback(); @State private var saving = false
    private let timer = Timer.publish(every: 1, on: .main, in: .common).autoconnect()
    var body: some View { NavigationStack { VStack(spacing: 18) {
        HStack { Text(String(format: "%02d:%02d", elapsed / 60, elapsed % 60)).font(.title.monospacedDigit().bold()); Spacer(); Text("\(index + 1)/\(exercises.count)").foregroundStyle(.secondary) }
        ProgressView(value: Double(index + 1), total: Double(max(exercises.count, 1))).tint(Color.hedefitGreen)
        if exercises.indices.contains(index) { let exercise = exercises[index]; VStack(spacing: 10) { Image(systemName: "figure.strengthtraining.traditional").font(.system(size: 70)).foregroundStyle(Color.hedefitGreen); Text(exercise.name).font(.largeTitle.bold()); Text("\(exercise.area) • Dinlenme \(exercise.restSeconds) sn").foregroundStyle(.secondary) }.frame(maxHeight: .infinity); List(0..<exercise.sets, id: \.self) { setIndex in SetInputRow(setNumber: setIndex + 1, exercise: exercise, sets: $sets, order: index) }.listStyle(.plain); HStack { Button("Önceki") { index = max(0, index - 1) }.disabled(index == 0); Spacer(); if index + 1 < exercises.count { Button("Sonraki") { index += 1 }.buttonStyle(HedefitButtonStyle()) } else { Button("Bitir") { finish() }.buttonStyle(HedefitButtonStyle()) } } }
    }.padding().navigationTitle("Aktif antrenman").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .cancellationAction) { Button("Kapat") { dismiss() } } }.onReceive(timer) { _ in elapsed += 1 }.interactiveDismissDisabled(saving) } }
    private func finish() { saving = true; if sets.isEmpty { for (order, exercise) in exercises.enumerated() { for number in 1...exercise.sets { sets.append(.init(exerciseID: exercise.id, exerciseName: exercise.name, exerciseOrder: order, setNumber: number, reps: Int(exercise.reps.filter(\.isNumber)))) } } }; Task { do { try await store.saveWorkout(sets: sets, seconds: elapsed, calories: max(1, elapsed / 8), feedback: feedback); dismiss() } catch { store.error = error.localizedDescription }; saving = false } }
}
struct SetInputRow: View { let setNumber: Int; let exercise: WorkoutExercise; @Binding var sets: [WorkoutSet]; let order: Int; @State private var kg = ""; @State private var reps = ""; var body: some View { HStack { Text("\(setNumber)").font(.headline).frame(width: 26); TextField("kg", text: $kg).keyboardType(.decimalPad).textFieldStyle(.roundedBorder); TextField("tekrar", text: $reps).keyboardType(.numberPad).textFieldStyle(.roundedBorder); Button { let row = WorkoutSet(exerciseID: exercise.id, exerciseName: exercise.name, exerciseOrder: order, setNumber: setNumber, weightKg: Double(kg), reps: Int(reps)); sets.removeAll { $0.exerciseID == exercise.id && $0.setNumber == setNumber }; sets.append(row) } label: { Image(systemName: sets.contains(where: { $0.exerciseID == exercise.id && $0.setNumber == setNumber }) ? "checkmark.circle.fill" : "circle") }.foregroundStyle(Color.hedefitGreen) } } }

struct NutritionView: View {
    @Environment(AppStore.self) private var store; @State private var showAdd = false
    private var totals: (Int, Double, Double, Double) { store.dashboard.nutritionLogs.reduce((0, 0, 0, 0)) { ($0.0 + $1.calories, $0.1 + $1.protein, $0.2 + $1.carbs, $0.3 + $1.fat) } }
    var body: some View { ScrollView { VStack(spacing: 18) {
        HStack { ProgressRing(value: Double(totals.0) / Double(store.dashboard.nutritionGoal.calories), color: Color.hedefitOrange, title: "Kalori", center: "\(totals.0)"); ProgressRing(value: totals.1 / Double(store.dashboard.nutritionGoal.protein), color: .pink, title: "Protein", center: "\(Int(totals.1))g"); ProgressRing(value: totals.2 / Double(store.dashboard.nutritionGoal.carbs), color: .blue, title: "Karb.", center: "\(Int(totals.2))g"); ProgressRing(value: totals.3 / Double(store.dashboard.nutritionGoal.fat), color: .yellow, title: "Yağ", center: "\(Int(totals.3))g") }.padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 22))
        HStack { VStack(alignment: .leading) { Text("Su takibi").font(.headline); Text("\(store.dashboard.waterMl) / \(store.settings.waterGoal) ml").foregroundStyle(.secondary) }; Spacer(); Button("−250") { Task { await store.addWater(-250) } }; Button("+250") { Task { await store.addWater(250) } }.buttonStyle(.borderedProminent) }.padding().background(.blue.opacity(0.1), in: RoundedRectangle(cornerRadius: 18))
        ForEach(["Kahvaltı", "Öğle", "Akşam", "Ara Öğün"], id: \.self) { meal in VStack(alignment: .leading, spacing: 10) { SectionHeader(title: meal); let logs = store.dashboard.nutritionLogs.filter { $0.meal.localizedCaseInsensitiveContains(meal) || (meal == "Ara Öğün" && $0.meal.lowercased().contains("ara")) }; if logs.isEmpty { Text("Henüz kayıt yok").font(.caption).foregroundStyle(.secondary) } else { ForEach(logs) { log in HStack { VStack(alignment: .leading) { Text(log.name); Text("\(Int(log.grams ?? 0)) g • P \(Int(log.protein))g  K \(Int(log.carbs))g  Y \(Int(log.fat))g").font(.caption).foregroundStyle(.secondary) }; Spacer(); Text("\(log.calories) kcal"); Menu { Button("Sil", role: .destructive) { Task { await store.deleteFood(log) } } } label: { Image(systemName: "ellipsis") } } } } }.padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 18)) }
    }.padding() }.navigationTitle("Beslenme").toolbar { Button { showAdd = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $showAdd) { AddFoodView() } }
}
struct AddFoodView: View { @Environment(AppStore.self) private var store; @Environment(\.dismiss) private var dismiss; @State private var text = ""; @State private var grams = 100.0; @State private var meal = "Kahvaltı"; var body: some View { NavigationStack { Form { Section("Yazarak ekle") { TextField("Örn. 2 yumurta ve peynir", text: $text, axis: .vertical); TextField("Gram", value: $grams, format: .number).keyboardType(.decimalPad); Picker("Öğün", selection: $meal) { ForEach(["Kahvaltı", "Öğle", "Akşam", "Ara Öğün"], id: \.self) { Text($0) } } }; Section { Text("Hedefit AI yazdığın öğünün porsiyonunu ve besin değerlerini tahmin eder. Kaydetmeden sonra günlüğünden düzenleyebilirsin.").font(.caption).foregroundStyle(.secondary) } }.navigationTitle("Öğün ekle").toolbar { ToolbarItem(placement: .cancellationAction) { Button("İptal") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("Hesapla ve kaydet") { Task { await store.addFood(text, grams: grams, meal: meal); if store.error == nil { dismiss() } } }.disabled(text.isEmpty) } } } } }

struct CoachView: View {
    @Environment(AppStore.self) private var store; @State private var input = ""
    var body: some View { VStack { ScrollViewReader { proxy in ScrollView { LazyVStack(spacing: 12) { ForEach(store.chat) { message in HStack { if message.fromUser { Spacer(minLength: 45) }; Text(message.text).padding(12).background(message.fromUser ? Color.hedefitGreen : Color.panel, in: RoundedRectangle(cornerRadius: 17)).foregroundStyle(message.fromUser ? .black : .primary); if !message.fromUser { Spacer(minLength: 45) } }.id(message.id) } }.padding() }.onChange(of: store.chat.count) { _, _ in if let id = store.chat.last?.id { withAnimation { proxy.scrollTo(id, anchor: .bottom) } } } }; HStack { TextField("Koçuna bir şey sor…", text: $input, axis: .vertical).hedefitField(); Button { let text = input; input = ""; Task { await store.sendChat(text) } } label: { Image(systemName: "arrow.up.circle.fill").font(.title).foregroundStyle(Color.hedefitGreen) }.disabled(input.trimmingCharacters(in: .whitespaces).isEmpty || store.loading) }.padding() }.navigationTitle("Hedefit Koç")
}
}

struct ProgressDashboardView: View {
    @Environment(AppStore.self) private var store; @State private var showMeasurement = false
    var body: some View { ScrollView { VStack(spacing: 18) {
        LazyVGrid(columns: [.init(.flexible()), .init(.flexible())]) { MetricCard(title: "Toplam antrenman", value: "\(store.dashboard.sessions.count)", icon: "dumbbell.fill"); MetricCard(title: "Toplam XP", value: "\(store.dashboard.gamificationTotalXp ?? 0)", icon: "star.fill", color: .yellow); MetricCard(title: "Rota mesafesi", value: String(format: "%.1f km", store.dashboard.routeActivities.reduce(0) { $0 + $1.distanceMeters } / 1000), icon: "map.fill", color: .blue); MetricCard(title: "Seri", value: "\(store.dashboard.streakDays) gün", icon: "flame.fill", color: .orange) }
        if !store.dashboard.measurements.isEmpty { VStack(alignment: .leading) { SectionHeader(title: "Kilo değişimi"); Chart(store.dashboard.measurements.compactMap { m in m.weightKg.map { (m.date, $0) } }, id: \.0) { item in LineMark(x: .value("Tarih", item.0), y: .value("Kilo", item.1)).foregroundStyle(Color.hedefitGreen); PointMark(x: .value("Tarih", item.0), y: .value("Kilo", item.1)).foregroundStyle(Color.hedefitGreen) }.frame(height: 190) }.padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 20)) }
        VStack(alignment: .leading, spacing: 10) { SectionHeader(title: "Son aktiviteler"); ForEach(store.dashboard.sessions.prefix(10)) { session in HStack { Image(systemName: session.manualActivityKey == nil ? "dumbbell.fill" : "figure.mixed.cardio").foregroundStyle(Color.hedefitGreen); VStack(alignment: .leading) { Text(session.exerciseNames.first ?? "Aktivite"); Text(session.completedAt.prefix(10)).font(.caption).foregroundStyle(.secondary) }; Spacer(); Text("\(session.calories) kcal") } } }.padding().background(Color.panel, in: RoundedRectangle(cornerRadius: 20))
        NavigationLink { GoalJourneyView() } label: { Label("Hedef yolculuğu", systemImage: "flag.checkered").frame(maxWidth: .infinity) }.buttonStyle(HedefitButtonStyle())
    }.padding() }.navigationTitle("İlerleme").toolbar { Button { showMeasurement = true } label: { Image(systemName: "plus") } }.sheet(isPresented: $showMeasurement) { MeasurementView() } }
}
