export type CoachMessage = { role: "user" | "assistant"; text: string };

export function localCoachReply(question: string, locale: "tr" | "en" = "tr") {
  if (locale === "en") {
    const normalized = question.toLocaleLowerCase("en-US");
    if (!/workout|train|exercise|gym|fitness|weight|calorie|protein|nutrition|meal|food|diet|macro|cardio|run|walk|step|sleep|rest|recover|pain|hurt|injur|fatigue|muscle|set|rep/.test(normalized)) {
      return "I’m Fit Coach, so I can only help with training, nutrition, recovery, and healthy habits. Ask me about your goal, workout, or meals and I’ll help.";
    }
    if (/protein|how much protein/.test(normalized)) return "For a healthy adult who trains regularly, a practical daily protein range is 1.6–2.2 g per kg of body weight. Spread it across 3–4 meals; foods such as yoghurt, eggs, lean meat, fish, legumes and tofu can help. For kidney disease or a clinician-set diet, follow your clinician’s plan instead.";
    if (/calorie|calories|deficit/.test(normalized)) return "For fat loss, use a modest calorie deficit rather than an extreme cut; consistent meals, protein, steps and resistance training matter more than a crash diet. Use Hedefit’s calorie target as the reference, and adjust from several weeks of weight trend rather than one day.";
    if (/carb|carbohydrate/.test(normalized)) return "Carbohydrates support training energy. Choose mostly potatoes, rice, oats, whole grains, fruit and legumes; place a portion before or after training when it helps your energy and recovery. The right amount depends on your calorie target and activity.";
    if (/fat|healthy fat/.test(normalized)) return "Dietary fat supports normal health and helps meals feel satisfying. Prefer olive oil, nuts, seeds, avocado, eggs and oily fish; keep portions intentional because fats are calorie-dense.";
    if (/water|hydration/.test(normalized)) return "Make water your default drink and increase it around training, heat, and long walks. A simple check is pale-yellow urine and regular drinking through the day; Hedefit’s water log is a practical way to stay consistent.";
    if (/before.*workout|pre.?workout/.test(normalized)) return "Before training, choose an easy-to-digest meal or snack with carbohydrate and some protein 1–3 hours beforehand: for example yoghurt with fruit, oats, or a sandwich. Keep the portion smaller if you are training soon.";
    if (/after.*workout|post.?workout/.test(normalized)) return "After training, eat a normal meal with protein and carbohydrates when practical. You do not need a perfect timing window—your full-day protein and calorie consistency matter most.";
    if (/lose weight|fat loss|cutting/.test(normalized)) return "Aim for a sustainable calorie deficit, regular steps, resistance training and adequate protein. Fat loss cannot be targeted to one body part; track your overall weekly trend and adjust gradually.";
    if (/gain muscle|bulk|build muscle/.test(normalized)) return "Build muscle with progressive resistance training, enough protein, good sleep and a small calorie surplus if your goal is weight gain. Add load or reps only when form stays controlled; consistency beats frequent program changes.";
    if (/warm.?up/.test(normalized)) return "Warm up for 5–8 minutes with easy cardio, then do lighter practice sets of your first movement. The goal is to prepare the joints and pattern—not to tire yourself out.";
    if (/rest.*set|rest time/.test(normalized)) return "Rest about 60–120 seconds for most accessory sets and 2–3 minutes for challenging compound lifts. Start the next set when breathing is settled enough to keep good form.";
    if (/rpe/.test(normalized)) return "RPE describes how many quality reps you had left: RPE 7 usually means about 3 reps in reserve, while RPE 8 means about 2. Most working sets can live around RPE 6–8; avoid grinding every set.";
    if (/how often|frequency|days.*week/.test(normalized)) return "For most beginners, 2–4 resistance sessions per week is a strong start. Leave enough recovery between hard sessions for the same muscle group and build the habit before adding more volume.";
    if (/pain|hurt|injur|dizz|chest/.test(normalized)) return "If you have sharp pain, dizziness, or chest pain, stop the workout. If the pain doesn't go away, see a health professional; today, avoid increasing load and consider only light, pain-free movements.";
    if (/rest|sleep|tired|fatigue/.test(normalized)) return "Don't increase load if fatigue is high. Rest 60–120 seconds between sets until your breathing returns to normal; focus today on controlled form and recovery rather than performance.";
    if (/easier|alternative|can'?t|cannot/.test(normalized)) return "Make the exercise easier with a shorter range of motion, lighter weight, or an assisted variation. If you can't keep control through the rep, end the set and switch to a pain-free alternative.";
    if (/easy|harder|increase|progress/.test(normalized)) return "If you've completed two workouts with good form at the same reps around RPE 6–7, increase only one variable: 1–2 reps or a small weight increase. Keep your current level if there's pain or high fatigue.";
    return "For today's program, warm up for 5–8 minutes first, perform the exercises with controlled form, and choose a load where the last 2 reps get noticeably harder without breaking form. Reduce intensity if there's pain or unusual fatigue.";
  }
  const normalized = question.toLocaleLowerCase("tr-TR");
  if (!/antrenman|spor|egzersiz|hareket|fitness|salon|kas|kilo|kalori|protein|beslen|öğün|yemek|diyet|makro|kardiyo|koşu|yürü|adım|uyku|dinlen|toparlan|ağrı|acı|yaralan|set|tekrar/.test(normalized)) {
    return "Ben Fit Koçum; yalnızca antrenman, beslenme, toparlanma ve sağlıklı alışkanlıklarda yardımcı olabilirim. Hedefin, antrenmanın veya öğünlerinle ilgili bir soru sorarsan birlikte bakalım.";
  }
  if (/protein|ne kadar protein/.test(normalized)) return "Düzenli antrenman yapan sağlıklı bir yetişkin için günlük protein adına pratik aralık, kilo başına 1,6–2,2 gramdır. Bunu 3–4 öğüne yay; yoğurt, yumurta, yağsız et, balık, bakliyat ve tofu iyi seçeneklerdir. Böbrek hastalığı veya klinik diyet varsa kendi uzmanının planını izle.";
  if (/kalori|kalorim|açık/.test(normalized)) return "Kilo vermede aşırı kısıtlama yerine sürdürülebilir, ılımlı bir kalori açığı hedefle. Düzenli öğün, protein, adım ve direnç antrenmanı birlikte çalışır. Hedefit'in kalori hedefini temel al; tek güne değil, birkaç haftalık kilo trendine göre ayarlama yap.";
  if (/karbonhidrat|karb/.test(normalized)) return "Karbonhidrat antrenman enerjisini destekler. Patates, pirinç, yulaf, tam tahıl, meyve ve bakliyatı çoğunlukla tercih et; enerji ve toparlanma için antrenman öncesi veya sonrasına bir porsiyon koyabilirsin. Miktar, kalori hedefin ve aktivitenle değişir.";
  if (/yağ|sağlıklı yağ/.test(normalized)) return "Beslenmedeki yağlar normal vücut işlevleri ve tokluk için önemlidir. Zeytinyağı, kuruyemiş, tohum, avokado, yumurta ve yağlı balığı tercih et; yağlar kalorice yoğun olduğu için porsiyonu bilinçli tut.";
  if (/su|hidrasyon/.test(normalized)) return "Suyu gün içindeki ana içeceğin yap; antrenman, sıcak hava ve uzun yürüyüşlerde miktarı artır. Açık sarı idrar ve gün içine yayılmış içme basit göstergelerdir; Hedefit'teki su kaydı düzen kurmana yardımcı olur.";
  if (/antrenman.*önce|spor.*önce|pre.?workout/.test(normalized)) return "Antrenmandan 1–3 saat önce, karbonhidrat ve biraz protein içeren kolay sindirilen bir öğün veya ara öğün seç: meyveli yoğurt, yulaf ya da sandviç gibi. Antrenmana az kaldıysa porsiyonu küçük tut.";
  if (/antrenman.*sonra|spor.*sonra|post.?workout/.test(normalized)) return "Antrenman sonrasında uygun olduğunda protein ve karbonhidrat içeren normal bir öğün ye. Mükemmel bir zaman penceresine gerek yok; günün toplam protein ve kalori düzeni daha önemlidir.";
  if (/kilo ver|yağ yak|zayıfla/.test(normalized)) return "Sürdürülebilir kalori açığı, düzenli adım, direnç antrenmanı ve yeterli proteinle ilerle. Yağ kaybı tek bir bölgeden hedeflenemez; genel haftalık trendini takip edip küçük ayarlamalar yap.";
  if (/kas al|kas yap|bulk|hacim/.test(normalized)) return "Kas için düzenli direnç antrenmanı, yeterli protein, iyi uyku ve kilo alma hedefinde küçük bir kalori fazlası gerekir. Formun bozulmadan tamamladığın setlerde ağırlığı veya tekrarı yavaşça artır; sürekli program değiştirmek yerine düzenli kal.";
  if (/ısınma|isinma/.test(normalized)) return "5–8 dakika hafif kardiyo yap, ardından ilk hareketinin daha hafif hazırlık setlerini uygula. Amaç eklemleri ve hareket paternini hazırlamak; kendini yormak değil.";
  if (/dinlenme.*set|set.*dinlen|kaç dakika dinlen/.test(normalized)) return "Çoğu yardımcı hareket setinde 60–120 saniye, zor bileşik hareketlerde 2–3 dakika dinlen. Nefesin ve formun toparlanınca sonraki sete geç.";
  if (/rpe/.test(normalized)) return "RPE, sette kaç kaliteli tekrarın kaldığını anlatır: RPE 7 yaklaşık 3 tekrar, RPE 8 yaklaşık 2 tekrar yedekte demektir. Çoğu çalışma setini RPE 6–8 civarında tut; her seti tükenişe götürme.";
  if (/kaç gün|haftada.*spor|sıklık/.test(normalized)) return "Başlangıç için haftada 2–4 direnç antrenmanı iyi bir aralıktır. Aynı kas grubunun zor seansları arasında toparlanmaya zaman tanı; önce alışkanlığı kur, sonra hacmi artır.";
  if (/ağrı|acı|yaralan|baş dön|göğüs/.test(normalized)) return "Keskin ağrı, baş dönmesi veya göğüs ağrısı varsa antrenmanı durdur. Ağrı geçmiyorsa bir sağlık uzmanına danış; bugün yük artırma ve yalnızca ağrısız, hafif hareketleri değerlendir.";
  if (/dinlen|uyku|yorgun/.test(normalized)) return "Yorgunluk yüksekse yükü artırma. Setler arasında nefesin normale yaklaşana kadar 60–120 saniye dinlen; bugün performanstan çok kontrollü form ve toparlanmaya odaklan.";
  if (/kolaylaştır|alternatif|yapam/.test(normalized)) return "Hareketi daha kısa hareket aralığı, daha düşük ağırlık veya destekli varyasyonla kolaylaştır. Tekrar boyunca kontrolü koruyamıyorsan seti bitir ve ağrısız alternatife geç.";
  if (/kolay|zorlaştır|artır|ilerle/.test(normalized)) return "Aynı tekrarları iyi formla ve RPE 6–7 civarında iki antrenman tamamladıysan yalnızca bir değişkeni artır: 1–2 tekrar veya küçük bir ağırlık artışı. Ağrı ya da yüksek yorgunluk varsa mevcut düzeyi koru.";
  return "Bugünkü programda önce 5–8 dakika ısın, hareketleri kontrollü formda uygula ve son 2 tekrar belirgin biçimde zorlaşsa da formun bozulmayacağı yükü seç. Ağrı veya olağandışı yorgunlukta yoğunluğu azalt.";
}
